### ISSUE TITLE
Document workaround for bin vs scripts directory when resolving eap-session-replication.war at deployment time

### ISSUE THREAD

**Issue by edburns** [Azure/rhel-jboss-templates#108]
## What is the problem
We discovered that, after publishing our BYOS artifacts (VMSS and multivm) as private plans in Azure Partner center, the resources under `/bin` directory is missing. If we tried to access the resources using URL, it returns error message as below:
```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```
## Root cause
In Azure Partner center some backend logic doesn't publish all directory packed in artifacts during private plan publishing (to be confirmed).
## Current workaround
For BYOS VMSS and multivm offers, we did the following steps to unblock ourselves for now.
1. Modify the file path in BYOS VMSS and multivm offers' `mainTemplate.bicep` file from `/bin` to `/scripts`.
2. Add additional steps in artifact building pipelines, move all files under `/bin` to `/scripts` and delete the `/bin`.
3. Apply the same changes as step 2 to validation pipelines since we also create artifacts in them.

The downside of this workaround:
* If users deploy with templates directly, they will encounter failures.
## What we plan to do
Raise feature requests to Azure Partner Center team or come up with an engineering plan after discussions.

**Comment by zhengchang907** [comment]
## What is the problem
We discovered that, after publishing our BYOS artifacts (VMSS and multivm) as private plans in Azure Partner center, the resources under `/bin` directory is missing. If we tried to access the resources using URL, it returns error message as below:
```
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```
## Root cause
In Azure Partner center some backend logic doesn't publish all directory packed in artifacts during private plan publishing (to be confirmed).
## Current workaround
For BYOS VMSS and multivm offers, we did the following steps to unblock ourselves for now.
1. Modify the file path in BYOS VMSS and multivm offers' `mainTemplate.bicep` file from `/bin` to `/scripts`.
2. Add additional steps in artifact building pipelines, move all files under `/bin` to `/scripts` and delete the `/bin`.
3. Apply the same changes as step 2 to validation pipelines since we also create artifacts in them.

The downside of this workaround:
* If users deploy with templates directly, they will encounter failures.
## What we plan to do
Raise feature requests to Azure Partner Center team or come up with an engineering plan after discussions.

**Comment by edburns** [comment]
@Copilot is this workaround still necessary?
